from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from lmdesktopplus.adapters.live_wallpaper import (
    LiveWallpaperAdapter,
    etch_hypr_rules,
    etch_launcher_script,
    ensure_hypr_live_source,
)


class LiveWallpaperEtchTests(unittest.TestCase):
    def test_etch_hypr_rules_owned_header(self):
        text = etch_hypr_rules()
        self.assertIn("Generated by LMDesktopPlus", text)
        self.assertIn("lmdesktopplus-livewall", text)
        self.assertIn("windowrulev2 = pin", text)

    def test_etch_launcher_prefers_mpvpaper_when_video(self):
        text = etch_launcher_script(
            python="/usr/bin/python3",
            intensity=40,
            mpvpaper="/usr/bin/mpvpaper",
            video=Path("/tmp/live-matrix.mp4"),
        )
        self.assertIn("mpvpaper", text)
        self.assertIn("--live-wallpaper", text)
        self.assertIn("--rain-intensity 40", text)

    def test_ensure_hypr_source_ownership_guard(self):
        with tempfile.TemporaryDirectory() as tmp:
            hypr = Path(tmp) / "hyprland.conf"
            hypr.write_text("# foreign\n", encoding="utf-8")
            source = "source = /tmp/hypr-live-wallpaper.conf"
            self.assertFalse(ensure_hypr_live_source(hypr, source))
            hypr.write_text("# LMDesktopPlus owned\n", encoding="utf-8")
            self.assertTrue(ensure_hypr_live_source(hypr, source))
            self.assertIn(source, hypr.read_text(encoding="utf-8"))


class LiveWallpaperAdapterTests(unittest.TestCase):
    @patch("lmdesktopplus.adapters.live_wallpaper.spawn", return_value=9090)
    def test_start_stop_roundtrip(self, spawn):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            hypr = root / "hyprland.conf"
            hypr.write_text("# LMDesktopPlus\n", encoding="utf-8")
            store = {
                "features": {"live_wallpaper": False},
                "appearance": {"rain_intensity": 60},
            }

            def getter():
                return {
                    "features": dict(store["features"]),
                    "appearance": dict(store["appearance"]),
                }

            def updater(patch):
                if "features" in patch:
                    store["features"].update(patch["features"])
                if "appearance" in patch:
                    store["appearance"].update(patch["appearance"])
                return getter()

            adapter = LiveWallpaperAdapter(
                settings_get=getter,
                settings_update=updater,
                config_dir=root,
                hypr_conf=hypr,
                mpvpaper="",
                python="/usr/bin/python3",
            )
            with patch.object(LiveWallpaperAdapter, "_running_pid", return_value=9090):
                started = adapter.command("start", {})
            self.assertTrue(started.get("ok"))
            self.assertTrue(store["features"]["live_wallpaper"])
            self.assertTrue((root / "hypr-live-wallpaper.conf").is_file())
            self.assertTrue((root / "live-wallpaper-generated.sh").is_file())
            self.assertIn("hypr-live-wallpaper.conf", hypr.read_text(encoding="utf-8"))
            spawn.assert_called()
            argv = spawn.call_args[0][0]
            self.assertIn("--live-wallpaper", argv)
            self.assertIn("60", argv)

            stopped = adapter.command("stop", {})
            self.assertTrue(stopped.get("ok"))
            self.assertFalse(store["features"]["live_wallpaper"])

    def test_default_feature_on_in_snapshot(self):
        adapter = LiveWallpaperAdapter(
            settings_get=lambda: {"features": {}, "appearance": {}},
            mpvpaper="",
        )
        snap = adapter.snapshot()
        self.assertTrue(snap["available"])
        self.assertTrue(snap["enabled"])
        self.assertIn("html", snap["backends"])
        self.assertFalse(snap["running"])

    def test_explicit_feature_off_in_snapshot(self):
        adapter = LiveWallpaperAdapter(
            settings_get=lambda: {"features": {"live_wallpaper": False}, "appearance": {}},
            mpvpaper="",
        )
        self.assertFalse(adapter.snapshot()["enabled"])


if __name__ == "__main__":
    unittest.main()
