from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from lmdesktopplus.adapters.keybinds import (
    MATRIX_CHORDS,
    ChordAdapter,
    etch_matrix_binds,
    ensure_matrix_chord_source,
    tune_neon_chord,
    weave_vapor_chords,
)


class NeonChordParserTests(unittest.TestCase):
    def test_tune_neon_chord_normalizes_modifiers(self):
        self.assertEqual(tune_neon_chord("super, return"), "SUPER, Return")
        self.assertEqual(tune_neon_chord("ALT, ctrl, a"), "ALT, CTRL, A")
        self.assertEqual(tune_neon_chord("SUPER, SPACE"), "SUPER, SPACE")

    def test_tune_neon_chord_rejects_shell_and_empty(self):
        self.assertIsNone(tune_neon_chord(""))
        self.assertIsNone(tune_neon_chord("SUPER, Return; rm -rf /"))
        self.assertIsNone(tune_neon_chord("SUPER, Return\nexec"))
        self.assertIsNone(tune_neon_chord("SUPER, `id`"))
        self.assertIsNone(tune_neon_chord("Return"))  # needs a modifier


class VaporWeaveTests(unittest.TestCase):
    def test_weave_vapor_chords_merges_combo_only(self):
        woven = weave_vapor_chords(
            MATRIX_CHORDS,
            {"terminal": {"combo": "SUPER, T", "dispatch": "exec, evil"}},
        )
        self.assertEqual(woven["terminal"]["combo"], "SUPER, T")
        self.assertEqual(woven["terminal"]["dispatch"], MATRIX_CHORDS["terminal"]["dispatch"])
        self.assertTrue(woven["terminal"]["overridden"])
        self.assertFalse(woven["rofi"]["overridden"])


class MatrixEtchTests(unittest.TestCase):
    def test_etch_matrix_binds_golden_header_and_lines(self):
        woven = weave_vapor_chords(MATRIX_CHORDS, {})
        text = etch_matrix_binds(woven)
        self.assertIn("# Generated by LMDesktopPlus.", text)
        self.assertIn("bind = SUPER, Return, exec, kitty", text)
        self.assertIn("bind = SUPER, SPACE, exec, rofi -show drun", text)
        self.assertIn("bind = SUPER, ESCAPE, exec, loginctl lock-session", text)
        # Stable order follows MATRIX_CHORDS insertion order.
        first = text.index("bind = SUPER, Return")
        second = text.index("bind = SUPER, SPACE")
        self.assertLess(first, second)


class MatrixSourceGuardTests(unittest.TestCase):
    def test_ensure_matrix_chord_source_only_on_owned_hypr(self):
        with tempfile.TemporaryDirectory() as tmp:
            hypr = Path(tmp) / "hyprland.conf"
            hypr.write_text("# foreign config\n", encoding="utf-8")
            source = "source = /tmp/hypr-binds.conf"
            self.assertFalse(ensure_matrix_chord_source(hypr, source))
            self.assertNotIn(source, hypr.read_text(encoding="utf-8"))

            hypr.write_text("# LMDesktopPlus owned\n", encoding="utf-8")
            self.assertTrue(ensure_matrix_chord_source(hypr, source))
            self.assertIn(source, hypr.read_text(encoding="utf-8"))
            # Idempotent
            self.assertFalse(ensure_matrix_chord_source(hypr, source))


class ChordAdapterTests(unittest.TestCase):
    def test_scan_synth_tune_melt_roundtrip(self):
        with tempfile.TemporaryDirectory() as tmp:
            home = Path(tmp)
            config = home / "lmdesktopplus"
            hypr_dir = home / "hypr"
            hypr_dir.mkdir()
            hypr = hypr_dir / "hyprland.conf"
            hypr.write_text("# LMDesktopPlus package\n", encoding="utf-8")

            with patch("lmdesktopplus.adapters.keybinds.app_config_dir", return_value=config), patch(
                "lmdesktopplus.adapters.keybinds.xdg_config_home", return_value=home
            ), patch("lmdesktopplus.adapters.keybinds.executable", return_value=None):
                adapter = ChordAdapter()
                snap = adapter.snapshot()
                self.assertTrue(snap["available"])
                self.assertIn("terminal", snap["chords"])
                self.assertFalse(snap["file_present"])
                self.assertFalse((config / "hypr-binds.conf").is_file())

                tuned = adapter.command(
                    "tune", {"id": "terminal", "combo": "super, t"}
                )
                self.assertTrue(tuned.get("ok"))
                self.assertEqual(tuned["chords"]["terminal"]["combo"], "SUPER, T")

                vapor = json.loads((config / "keybinds.json").read_text(encoding="utf-8"))
                self.assertEqual(vapor["terminal"]["combo"], "SUPER, T")
                conf = (config / "hypr-binds.conf").read_text(encoding="utf-8")
                self.assertIn("bind = SUPER, T, exec, kitty", conf)
                self.assertIn(
                    f"source = {config / 'hypr-binds.conf'}",
                    hypr.read_text(encoding="utf-8"),
                )

                melted = adapter.command("melt", {"id": "terminal"})
                self.assertTrue(melted.get("ok"))
                self.assertFalse(melted["chords"]["terminal"]["overridden"])
                vapor_after = json.loads((config / "keybinds.json").read_text(encoding="utf-8"))
                self.assertNotIn("terminal", vapor_after)

    def test_tune_rejects_unknown_chord_and_bad_neon(self):
        with tempfile.TemporaryDirectory() as tmp:
            config = Path(tmp) / "lmdesktopplus"
            with patch("lmdesktopplus.adapters.keybinds.app_config_dir", return_value=config), patch(
                "lmdesktopplus.adapters.keybinds.xdg_config_home",
                return_value=Path(tmp),
            ), patch("lmdesktopplus.adapters.keybinds.executable", return_value=None):
                adapter = ChordAdapter()
                bad_id = adapter.command("tune", {"id": "not-a-chord", "combo": "SUPER, A"})
                self.assertFalse(bad_id.get("ok"))
                self.assertEqual(bad_id.get("error_code"), "invalid_argument")
                bad_neon = adapter.command("tune", {"id": "terminal", "combo": "SUPER; rm"})
                self.assertFalse(bad_neon.get("ok"))

    def test_unknown_command_rejected(self):
        adapter = ChordAdapter()
        result = adapter.command("set", {})
        self.assertFalse(result.get("ok"))
        self.assertIn("unknown keybinds command", result.get("error", ""))


if __name__ == "__main__":
    unittest.main()
