from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from lmdesktopplus.adapters.idle import IdleAdapter, etch_swayidle_script


class IdleEtchTests(unittest.TestCase):
    def test_etch_swayidle_includes_timeouts(self):
        text = etch_swayidle_script(5, 15)
        self.assertIn("#!/usr/bin/env bash", text)
        self.assertIn("Generated by LMDesktopPlus", text)
        self.assertIn("timeout 300 'loginctl lock-session'", text)
        self.assertIn("timeout 900 'systemctl suspend'", text)

    def test_etch_swayidle_skips_zero_timers(self):
        text = etch_swayidle_script(0, 0)
        self.assertNotIn("timeout", text)
        self.assertIn("before-sleep", text)


class IdleAdapterTests(unittest.TestCase):
    def test_apply_writes_owned_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            store = {"behavior": {"idle_lock_minutes": 10, "idle_sleep_minutes": 20}}

            def getter():
                return {"behavior": dict(store["behavior"])}

            def updater(patch):
                store["behavior"].update(patch.get("behavior", {}))
                return {"behavior": dict(store["behavior"])}

            adapter = IdleAdapter(
                settings_get=getter,
                settings_update=updater,
                config_dir=root,
                gsettings="",
                swayidle="/usr/bin/swayidle",
            )
            result = adapter.command("apply", {})
            self.assertTrue(result.get("ok"))
            script = root / "swayidle-generated.sh"
            note = root / "idle-generated.conf"
            self.assertTrue(script.is_file())
            self.assertTrue(note.is_file())
            body = script.read_text(encoding="utf-8")
            self.assertIn("timeout 600", body)
            self.assertIn("timeout 1200", body)

    @patch("lmdesktopplus.adapters.idle.run_capture")
    def test_apply_cinnamon_gsettings_when_present(self, run_capture):
        run_capture.return_value = type("CP", (), {"returncode": 0, "stdout": "", "stderr": ""})()
        with tempfile.TemporaryDirectory() as tmp:
            adapter = IdleAdapter(
                settings_get=lambda: {"behavior": {}},
                settings_update=lambda patch: patch,
                config_dir=Path(tmp),
                gsettings="/usr/bin/gsettings",
                swayidle="",
            )
            result = adapter.command("apply", {"lock_minutes": 3, "sleep_minutes": 0})
            self.assertTrue(result.get("ok"))
            self.assertTrue(result.get("cinnamon_applied"))
            self.assertGreaterEqual(run_capture.call_count, 2)


if __name__ == "__main__":
    unittest.main()
