from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from .config import ACCENTS
from .util import app_config_dir, executable, run_capture, xdg_config_home


def apply(settings: dict[str, Any]) -> dict[str, Any]:
    appearance = settings.get("appearance", {})
    accent_name = appearance.get("accent", "mag")
    accent = ACCENTS.get(accent_name, ACCENTS["mag"])
    results: list[dict[str, Any]] = []
    results.append(_write_gtk_overlay(accent, appearance))
    results.append(_write_hypr_overlay(accent, appearance))
    if executable("hyprctl") and os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
        cp = run_capture(["hyprctl", "reload"], timeout=4)
        results.append({"target": "hyprland-reload", "ok": cp.returncode == 0, "error": cp.stderr.strip() if cp.returncode else None})
    return {"ok": all(row.get("ok", False) for row in results), "results": results}


def _write_gtk_overlay(accent: str, appearance: dict[str, Any]) -> dict[str, Any]:
    opacity = max(0.4, min(1.0, int(appearance.get("opacity", 90)) / 100.0))
    text = f"""/* Generated by LMDesktopPlus. */
@define-color lmdp_accent {accent};
@define-color lmdp_bg rgba(5, 6, 10, {opacity:.2f});
selection {{ background-color: @lmdp_accent; color: #05060a; }}
*:focus {{ outline-color: alpha(@lmdp_accent, 0.75); }}
tooltip {{ background-color: @lmdp_bg; border: 1px solid @lmdp_accent; }}
"""
    try:
        for version in ("gtk-3.0", "gtk-4.0"):
            folder = xdg_config_home() / version
            folder.mkdir(parents=True, exist_ok=True)
            (folder / "lmdesktopplus-generated.css").write_text(text, encoding="utf-8")
        return {"target": "gtk", "ok": True}
    except OSError as exc:
        return {"target": "gtk", "ok": False, "error": str(exc)}


def _write_hypr_overlay(accent: str, appearance: dict[str, Any]) -> dict[str, Any]:
    rgba = accent.lstrip("#") + "ff"
    gaps = 8 if appearance.get("gaps", True) else 0
    rounding = 10 if appearance.get("rounded", False) else 0
    blur = int(appearance.get("blur", 9))
    opacity = max(0.4, min(1.0, int(appearance.get("opacity", 90)) / 100.0))
    shadows = "true" if appearance.get("shadows", True) else "false"
    text = f"""# Generated by LMDesktopPlus UI.
general {{
  gaps_in = {max(0, gaps // 2)}
  gaps_out = {gaps}
  col.active_border = rgba({rgba})
}}
decoration {{
  rounding = {rounding}
  active_opacity = {opacity:.2f}
  inactive_opacity = {max(0.35, opacity - 0.08):.2f}
  shadow {{ enabled = {shadows} }}
  blur {{ enabled = {'true' if blur > 0 else 'false'}; size = {max(1, blur // 3)}; passes = {1 if blur < 12 else 2} }}
}}
"""
    try:
        dest = app_config_dir() / "hypr-generated.conf"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text, encoding="utf-8")
        hypr = xdg_config_home() / "hypr" / "hyprland.conf"
        source_line = f"source = {dest}"
        if hypr.exists():
            current = hypr.read_text(encoding="utf-8", errors="replace")
            # Only edit a config already marked as LMDesktopPlus-owned. Avoid
            # silently modifying an unrelated Hyprland setup.
            if "LMDesktopPlus" in current and source_line not in current:
                with hypr.open("a", encoding="utf-8") as handle:
                    handle.write(f"\n# LMDesktopPlus generated UI settings\n{source_line}\n")
        return {"target": "hyprland", "ok": True, "path": str(dest)}
    except OSError as exc:
        return {"target": "hyprland", "ok": False, "error": str(exc)}
