"""Idle / lock timer adapter — owned generated snippets only (Stage D Task 19).

@use levels: apply is low use; status/snapshot are medium use.
Never rewrites foreign swayidle configs — only LMDP-owned files under
`~/.config/lmdesktopplus/` plus optional Cinnamon gsettings for the current user.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path
from typing import Any

from ..fncache import UseLevel, register_fn
from ..util import app_config_dir, executable, run_capture
from .base import dispatch_command

_GENERATED_HEADER = "# Generated by LMDesktopPlus. Do not edit by hand — use Settings → Display.\n"


def clamp_idle_minutes(value: Any, *, lo: int, hi: int) -> int:
    # @use: medium use — purpose: sanitize idle timer integers from settings/UI
    try:
        minutes = int(value)
    except (TypeError, ValueError):
        return 0
    return max(lo, min(hi, minutes))


@register_fn(
    "idle.etch_swayidle_script",
    UseLevel.LOW,
    "Render owned swayidle-generated.sh contents from lock/sleep minutes",
)
def etch_swayidle_script(lock_minutes: int, sleep_minutes: int) -> str:
    """Build a runnable swayidle launcher script (owned file body)."""
    # @use: low use — purpose: generate Hyprland-side idle snippet text
    lines = [
        "#!/usr/bin/env bash",
        _GENERATED_HEADER.rstrip(),
        "set -euo pipefail",
        'SWAYIDLE="$(command -v swayidle || true)"',
        'if [[ -z "$SWAYIDLE" ]]; then',
        '  echo "swayidle not installed" >&2',
        "  exit 127",
        "fi",
        'exec "$SWAYIDLE" -w \\',
    ]
    # Emit timeout clauses only when timers are enabled (> 0).
    if lock_minutes > 0:
        secs = lock_minutes * 60
        lines.append(f"  timeout {secs} 'loginctl lock-session' \\")
    if sleep_minutes > 0:
        secs = sleep_minutes * 60
        lines.append(f"  timeout {secs} 'systemctl suspend' \\")
    lines.append("  before-sleep 'loginctl lock-session'")
    lines.append("")
    return "\n".join(lines)


@register_fn(
    "idle.etch_idle_note",
    UseLevel.LOW,
    "Render idle-generated.conf human-readable apply note",
)
def etch_idle_note(lock_minutes: int, sleep_minutes: int, *, cinnamon: bool, swayidle: bool) -> str:
    # @use: low use — purpose: document what IdleAdapter.apply wrote
    return (
        _GENERATED_HEADER
        + f"lock_minutes = {lock_minutes}\n"
        + f"sleep_minutes = {sleep_minutes}\n"
        + f"cinnamon_gsettings = {str(cinnamon).lower()}\n"
        + f"swayidle_script = {str(swayidle).lower()}\n"
        + "swayidle_path = ~/.config/lmdesktopplus/swayidle-generated.sh\n"
    )


class IdleAdapter:
    """Apply idle lock/sleep timers to owned files + best-effort Cinnamon gsettings."""

    id = "idle"

    def __init__(
        self,
        *,
        settings_get=None,
        settings_update=None,
        config_dir: Path | None = None,
        gsettings: str | None = None,
        swayidle: str | None = None,
    ) -> None:
        self._settings_get = settings_get
        self._settings_update = settings_update
        self._config_dir = config_dir
        self.gsettings = gsettings if gsettings is not None else executable("gsettings")
        self.swayidle = swayidle if swayidle is not None else executable("swayidle")

    def _root(self) -> Path:
        return self._config_dir if self._config_dir is not None else app_config_dir()

    def available(self) -> bool:
        return True

    def _behavior(self) -> dict[str, Any]:
        if not self._settings_get:
            return {}
        settings = self._settings_get() or {}
        behavior = settings.get("behavior") or {}
        return behavior if isinstance(behavior, dict) else {}

    def snapshot(self) -> dict[str, Any]:
        # @use: medium use — purpose: Display tab idle panel state
        behavior = self._behavior()
        lock_m = clamp_idle_minutes(behavior.get("idle_lock_minutes", 0), lo=0, hi=120)
        sleep_m = clamp_idle_minutes(behavior.get("idle_sleep_minutes", 0), lo=0, hi=240)
        script = self._root() / "swayidle-generated.sh"
        return {
            "available": True,
            "backend": "generated-snippets",
            "lock_minutes": lock_m,
            "sleep_minutes": sleep_m,
            "swayidle_available": bool(self.swayidle),
            "gsettings_available": bool(self.gsettings),
            "script_path": str(script),
            "script_present": script.is_file(),
            "desktop": (os.environ.get("XDG_CURRENT_DESKTOP") or "").lower(),
        }

    def command(self, name: str, payload: dict[str, Any]) -> dict[str, Any]:
        return dispatch_command(self._commands(), name, payload, adapter_id=self.id)

    def _commands(self) -> dict[str, Any]:
        return {
            "status": lambda _payload: {"ok": True, **self.snapshot()},
            "apply": lambda payload: self._apply_idle(payload),
        }

    def _apply_idle(self, payload: dict[str, Any]) -> dict[str, Any]:
        # @use: low use — purpose: persist timers + etch owned idle snippets
        behavior = self._behavior()
        lock_m = clamp_idle_minutes(
            payload.get("lock_minutes", behavior.get("idle_lock_minutes", 0)),
            lo=0,
            hi=120,
        )
        sleep_m = clamp_idle_minutes(
            payload.get("sleep_minutes", behavior.get("idle_sleep_minutes", 0)),
            lo=0,
            hi=240,
        )
        # Persist into settings when a store hook is wired.
        if self._settings_update:
            self._settings_update(
                {
                    "behavior": {
                        "idle_lock_minutes": lock_m,
                        "idle_sleep_minutes": sleep_m,
                    }
                }
            )
        root = self._root()
        root.mkdir(parents=True, exist_ok=True)
        script_path = root / "swayidle-generated.sh"
        note_path = root / "idle-generated.conf"
        script_body = etch_swayidle_script(lock_m, sleep_m)
        script_path.write_text(script_body, encoding="utf-8")
        try:
            script_path.chmod(script_path.stat().st_mode | stat.S_IXUSR)
        except OSError:
            pass
        cinnamon_ok = self._apply_cinnamon(lock_m)
        note_path.write_text(
            etch_idle_note(
                lock_m,
                sleep_m,
                cinnamon=cinnamon_ok,
                swayidle=bool(self.swayidle),
            ),
            encoding="utf-8",
        )
        snap = self.snapshot()
        return {"ok": True, **snap, "cinnamon_applied": cinnamon_ok}

    def _apply_cinnamon(self, lock_minutes: int) -> bool:
        # @use: low use — purpose: best-effort Cinnamon idle-delay / lock gsettings
        if not self.gsettings:
            return False
        seconds = max(0, lock_minutes * 60)
        try:
            # idle-delay 0 disables the idle timer in Cinnamon.
            cp1 = run_capture(
                [
                    self.gsettings,
                    "set",
                    "org.cinnamon.desktop.session",
                    "idle-delay",
                    str(seconds),
                ],
                timeout=3,
            )
            cp2 = run_capture(
                [
                    self.gsettings,
                    "set",
                    "org.cinnamon.desktop.screensaver",
                    "lock-enabled",
                    "true" if lock_minutes > 0 else "false",
                ],
                timeout=3,
            )
            return cp1.returncode == 0 and cp2.returncode == 0
        except (OSError, RuntimeError):
            return False
