"""Vapor//matrix Hyprland chord editor (Stage C keybinds).

Typology nomenclature
---------------------
| Term    | Meaning |
|---------|---------|
| chord   | One bind: id + neon combo + dispatch + label |
| neon    | Normalized modifier+key combo string |
| vapor   | User override layer (`keybinds.json`) |
| matrix  | Canonical catalog + generated `hypr-binds.conf` |
| weave   | Merge matrix defaults with vapor overrides |
| etch    | Render conf text from effective chords |
| tune    | Set a single chord's neon combo |
| melt    | Dissolve vapor overrides back to matrix defaults |
| synth   | Persist etched overlay + ensure hypr source line |
| pulse   | Best-effort `hyprctl reload` after synth |
| scan    | Snapshot effective chords for the UI |
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from ..util import (
    app_config_dir,
    atomic_write_json,
    executable,
    read_json,
    run_capture,
    xdg_config_home,
)
from .base import command_error, dispatch_command

# Canonical matrix catalog — UI and file generation both consume this map.
MATRIX_CHORDS: dict[str, dict[str, str]] = {
    "terminal": {
        "combo": "SUPER, Return",
        "dispatch": "exec, kitty",
        "label": "Terminal",
    },
    "rofi": {
        "combo": "SUPER, SPACE",
        "dispatch": "exec, rofi -show drun",
        "label": "Launcher",
    },
    "agent": {
        "combo": "SUPER, A",
        "dispatch": "exec, lmdesktopplus",
        "label": "Agent surface",
    },
    "kill": {
        "combo": "SUPER, Q",
        "dispatch": "killactive,",
        "label": "Close window",
    },
    "fullscreen": {
        "combo": "SUPER, F",
        "dispatch": "fullscreen,",
        "label": "Fullscreen",
    },
    "float": {
        "combo": "SUPER, V",
        "dispatch": "togglefloating,",
        "label": "Toggle floating",
    },
    "lock": {
        "combo": "SUPER, ESCAPE",
        "dispatch": "exec, loginctl lock-session",
        "label": "System lock",
    },
}

ALLOWED_DISPATCH_PREFIXES: tuple[str, ...] = (
    "exec,",
    "killactive,",
    "fullscreen,",
    "togglefloating,",
    "workspace,",
    "movetoworkspace,",
)

_MODIFIERS = frozenset({"SUPER", "ALT", "CTRL", "SHIFT"})
_NAMED_KEYS = {
    "RETURN": "Return",
    "SPACE": "SPACE",
    "ESCAPE": "ESCAPE",
    "TAB": "TAB",
    "BACKSPACE": "BackSpace",
    "DELETE": "Delete",
    "INSERT": "Insert",
    "HOME": "Home",
    "END": "End",
    "PAGEUP": "Page_Up",
    "PAGEDOWN": "Page_Down",
    "UP": "Up",
    "DOWN": "Down",
    "LEFT": "Left",
    "RIGHT": "Right",
    "PRINT": "Print",
}
_COMBO_METACHARS = re.compile(r"[;\n\r`$|&<>\\\"']")
_KEY_TOKEN = re.compile(r"^[A-Za-z0-9_]+$")
_GENERATED_HEADER = (
    "# Generated by LMDesktopPlus. Do not edit by hand — use Settings → Keybinds.\n"
)


def tune_neon_chord(raw: Any) -> str | None:
    """Normalize a neon combo; reject empty / metachar / modifier-less values."""
    if not isinstance(raw, str):
        return None
    text = raw.strip()
    if not text or _COMBO_METACHARS.search(text):
        return None
    parts = [part.strip() for part in text.split(",") if part.strip()]
    if len(parts) < 2:
        return None
    mods: list[str] = []
    for token in parts[:-1]:
        upper = token.upper()
        if upper not in _MODIFIERS or upper in mods:
            return None
        mods.append(upper)
    key_raw = parts[-1]
    key_upper = key_raw.upper()
    if key_upper in _NAMED_KEYS:
        key = _NAMED_KEYS[key_upper]
    elif len(key_raw) == 1 and key_raw.isalnum():
        key = key_raw.upper()
    elif _KEY_TOKEN.match(key_raw) and len(key_raw) <= 16:
        key = key_raw
    else:
        return None
    return ", ".join([*mods, key])


def weave_vapor_chords(
    matrix: dict[str, dict[str, str]],
    vapor: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    """Merge matrix defaults with vapor overrides (combo only; dispatch stays matrix)."""
    woven: dict[str, dict[str, Any]] = {}
    for chord_id, spec in matrix.items():
        override = vapor.get(chord_id) if isinstance(vapor, dict) else None
        combo = spec["combo"]
        overridden = False
        if isinstance(override, dict):
            neon = tune_neon_chord(override.get("combo"))
            if neon:
                combo = neon
                overridden = neon != spec["combo"]
        woven[chord_id] = {
            "id": chord_id,
            "combo": combo,
            "dispatch": spec["dispatch"],
            "label": spec["label"],
            "overridden": overridden,
        }
    return woven


def etch_matrix_binds(woven: dict[str, dict[str, Any]]) -> str:
    """Render owned hypr-binds.conf text from woven chords."""
    lines = [_GENERATED_HEADER.rstrip(), ""]
    for chord_id in MATRIX_CHORDS:
        row = woven[chord_id]
        dispatch = row["dispatch"]
        if not any(dispatch.startswith(prefix) for prefix in ALLOWED_DISPATCH_PREFIXES):
            continue
        lines.append(f"bind = {row['combo']}, {dispatch}")
    lines.append("")
    return "\n".join(lines)


def ensure_matrix_chord_source(hypr_path: Path, source_line: str) -> bool:
    """Append source line only into LMDesktopPlus-owned hyprland.conf. Returns True if written."""
    if not hypr_path.exists():
        return False
    try:
        current = hypr_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    if "LMDesktopPlus" not in current or source_line in current:
        return False
    try:
        with hypr_path.open("a", encoding="utf-8") as handle:
            handle.write(
                "\n# LMDesktopPlus vapor//matrix chord overlay\n"
                f"{source_line}\n"
            )
    except OSError:
        return False
    return True


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    try:
        tmp.chmod(0o600)
    except OSError:
        pass
    tmp.replace(path)


def load_vapor_overrides(path: Path) -> dict[str, Any]:
    raw = read_json(path, {})
    return raw if isinstance(raw, dict) else {}


def synth_vapor_overrides(path: Path, vapor: dict[str, Any]) -> None:
    atomic_write_json(path, vapor)


class ChordAdapter:
    """Editable Hyprland chords via owned overlay — vapor//matrix typology."""

    id = "keybinds"

    def __init__(
        self,
        *,
        config_dir: Path | None = None,
        hypr_conf: Path | None = None,
        hyprctl: str | None = None,
        pulse_reload: bool = True,
    ) -> None:
        self._config_dir = config_dir
        self._hypr_conf = hypr_conf
        self._hyprctl = hyprctl
        self._pulse_reload = pulse_reload

    def _root(self) -> Path:
        return self._config_dir if self._config_dir is not None else app_config_dir()

    def matrix_path(self) -> Path:
        return self._root() / "hypr-binds.conf"

    def vapor_path(self) -> Path:
        return self._root() / "keybinds.json"

    def hypr_path(self) -> Path:
        if self._hypr_conf is not None:
            return self._hypr_conf
        return xdg_config_home() / "hypr" / "hyprland.conf"

    def available(self) -> bool:
        return True

    def snapshot(self) -> dict[str, Any]:
        # Read-only: never etch on poll. install.sh / tune / melt / synth write.
        woven = self._woven()
        path = self.matrix_path()
        source_line = f"source = {path}"
        hypr = self.hypr_path()
        sourced = False
        if hypr.exists():
            try:
                sourced = source_line in hypr.read_text(encoding="utf-8", errors="replace")
            except OSError:
                sourced = False
        return {
            "available": True,
            "backend": "hypr-binds",
            "chords": woven,
            "chord_order": list(MATRIX_CHORDS.keys()),
            "file": str(path),
            "vapor_file": str(self.vapor_path()),
            "file_present": path.is_file(),
            "sourced": sourced,
        }

    def command(self, name: str, payload: dict[str, Any]) -> dict[str, Any]:
        return dispatch_command(self._commands(), name, payload, adapter_id=self.id)

    def _commands(self) -> dict[str, Any]:
        return {
            "scan": lambda _payload: self._scan_chords(),
            "tune": lambda payload: self._tune_chord(payload),
            "melt": lambda payload: self._melt_chord(payload),
            "synth": lambda _payload: self._synth_matrix(),
        }

    def _woven(self) -> dict[str, dict[str, Any]]:
        return weave_vapor_chords(MATRIX_CHORDS, load_vapor_overrides(self.vapor_path()))

    def _scan_chords(self) -> dict[str, Any]:
        snap = self.snapshot()
        return {"ok": True, **snap}

    def _tune_chord(self, payload: dict[str, Any]) -> dict[str, Any]:
        chord_id = payload.get("id")
        if not isinstance(chord_id, str) or chord_id not in MATRIX_CHORDS:
            return command_error("invalid_argument", "unknown chord id")
        neon = tune_neon_chord(payload.get("combo"))
        if neon is None:
            return command_error("invalid_argument", "invalid neon combo")
        vapor = load_vapor_overrides(self.vapor_path())
        if neon == MATRIX_CHORDS[chord_id]["combo"]:
            vapor.pop(chord_id, None)
        else:
            vapor[chord_id] = {"combo": neon}
        synth_vapor_overrides(self.vapor_path(), vapor)
        result = self._synth_matrix()
        result["chords"] = self._woven()
        return result

    def _melt_chord(self, payload: dict[str, Any]) -> dict[str, Any]:
        chord_id = payload.get("id")
        vapor = load_vapor_overrides(self.vapor_path())
        if chord_id is None or chord_id == "" or chord_id == "*":
            vapor = {}
        elif isinstance(chord_id, str) and chord_id in MATRIX_CHORDS:
            vapor.pop(chord_id, None)
        elif isinstance(chord_id, str):
            return command_error("invalid_argument", "unknown chord id")
        else:
            return command_error("invalid_argument", "invalid chord id")
        synth_vapor_overrides(self.vapor_path(), vapor)
        result = self._synth_matrix()
        result["chords"] = self._woven()
        return result

    def _synth_matrix(self, *, pulse: bool | None = None) -> dict[str, Any]:
        woven = self._woven()
        text = etch_matrix_binds(woven)
        path = self.matrix_path()
        _atomic_write_text(path, text)
        source_line = f"source = {path}"
        appended = ensure_matrix_chord_source(self.hypr_path(), source_line)
        did_pulse = False
        if pulse if pulse is not None else self._pulse_reload:
            did_pulse = self._pulse_hyprland()
        return {
            "ok": True,
            "file": str(path),
            "sourced_appended": appended,
            "pulsed": did_pulse,
            "chords": woven,
        }

    def _pulse_hyprland(self) -> bool:
        hyprctl = self._hyprctl
        if hyprctl is None:
            hyprctl = executable("hyprctl")
        if not hyprctl:
            return False
        try:
            cp = run_capture([hyprctl, "reload"], timeout=3)
            return cp.returncode == 0
        except (OSError, RuntimeError):
            return False
