"""Live matrix wallpaper — HTML/DV.rain window or optional mpvpaper (Stage D Task 22).

Preoptimized: clamp_int/parse_int intensity; ternary pid/backend gates.
Feature-flagged (`features.live_wallpaper`, default on). Writes only owned files
under `~/.config/lmdesktopplus/` and appends a hypr `source=` line when the
hyprland.conf is already LMDesktopPlus-owned. Start is still explicit from the UI
so enabling the flag alone does not spawn a wallpaper process.
"""

from __future__ import annotations

import os
import signal
import stat
import sys
import time
from pathlib import Path
from typing import Any

from ..fncache import UseLevel, register_fn
from ..preopt import clamp_int, parse_int
from ..util import app_config_dir, app_data_dir, executable, spawn, xdg_config_home
from .base import command_error, dispatch_command

_GENERATED_HEADER = (
    "# Generated by LMDesktopPlus. Do not edit by hand — use Settings → Appearance.\n"
)
_WM_CLASS = "lmdesktopplus-livewall"
_PID_NAME = "live-wallpaper.pid"


@register_fn(
    "live_wallpaper.etch_hypr_rules",
    UseLevel.LOW,
    "Render owned hypr-live-wallpaper.conf window rules",
)
def etch_hypr_rules() -> str:
    # @use: low use — purpose: pin HTML live wallpaper window behind the desktop
    return (
        _GENERATED_HEADER
        + f"# Live wallpaper window class: {_WM_CLASS}\n"
        + f"windowrulev2 = float, class:^({_WM_CLASS})$\n"
        + f"windowrulev2 = pin, class:^({_WM_CLASS})$\n"
        + f"windowrulev2 = noborder, class:^({_WM_CLASS})$\n"
        + f"windowrulev2 = noshadow, class:^({_WM_CLASS})$\n"
        + f"windowrulev2 = nofocus, class:^({_WM_CLASS})$\n"
        + f"windowrulev2 = opaque, class:^({_WM_CLASS})$\n"
        + f"windowrulev2 = size 100% 100%, class:^({_WM_CLASS})$\n"
        + f"windowrulev2 = move 0 0, class:^({_WM_CLASS})$\n"
    )


def ensure_hypr_live_source(hypr_path: Path, source_line: str) -> bool:
    """Append source line only into LMDesktopPlus-owned hyprland.conf."""
    if not hypr_path.exists():
        return False
    try:
        current = hypr_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    if "LMDesktopPlus" not in current or source_line in current:
        return False
    try:
        with hypr_path.open("a", encoding="utf-8") as handle:
            handle.write(
                "\n# LMDesktopPlus live wallpaper window rules\n"
                f"{source_line}\n"
            )
    except OSError:
        return False
    return True


@register_fn(
    "live_wallpaper.etch_launcher_script",
    UseLevel.LOW,
    "Render live-wallpaper-generated.sh (html or mpvpaper backends)",
)
def etch_launcher_script(
    *,
    python: str,
    intensity: int,
    mpvpaper: str | None,
    video: Path | None,
) -> str:
    # @use: low use — purpose: owned launcher preferring mpvpaper when video exists
    lines = [
        "#!/usr/bin/env bash",
        _GENERATED_HEADER.rstrip(),
        "set -euo pipefail",
        f'PIDFILE="${{XDG_CONFIG_HOME:-$HOME/.config}}/lmdesktopplus/{_PID_NAME}"',
        'mkdir -p "$(dirname "$PIDFILE")"',
        'if [[ -f "$PIDFILE" ]]; then',
        '  old="$(cat "$PIDFILE" 2>/dev/null || true)"',
        '  if [[ -n "$old" ]] && kill -0 "$old" 2>/dev/null; then',
        '    kill "$old" 2>/dev/null || true',
        "    sleep 0.2",
        "  fi",
        '  rm -f "$PIDFILE"',
        "fi",
    ]
    if mpvpaper and video is not None:
        lines += [
            f'MPVPAPER="{mpvpaper}"',
            f'VIDEO="{video}"',
            'if [[ -x "$MPVPAPER" && -f "$VIDEO" ]]; then',
            '  "$MPVPAPER" -o "no-audio --loop" "*" "$VIDEO" &',
            '  echo $! > "$PIDFILE"',
            "  exit 0",
            "fi",
        ]
    lines += [
        f'exec "{python}" -m lmdesktopplus --live-wallpaper --rain-intensity {int(intensity)}',
        "",
    ]
    return "\n".join(lines)


class LiveWallpaperAdapter:
    """Start/stop feature-flagged live matrix wallpaper (default on)."""

    id = "live_wallpaper"

    def __init__(
        self,
        *,
        settings_get=None,
        settings_update=None,
        config_dir: Path | None = None,
        hypr_conf: Path | None = None,
        mpvpaper: str | None = None,
        python: str | None = None,
    ) -> None:
        self._settings_get = settings_get
        self._settings_update = settings_update
        self._config_dir = config_dir
        self._hypr_conf = hypr_conf
        self.mpvpaper = mpvpaper if mpvpaper is not None else executable("mpvpaper")
        self.python = python or sys.executable or "python3"

    def _root(self) -> Path:
        return self._config_dir if self._config_dir is not None else app_config_dir()

    def _hypr_path(self) -> Path:
        if self._hypr_conf is not None:
            return self._hypr_conf
        return xdg_config_home() / "hypr" / "hyprland.conf"

    def _pid_path(self) -> Path:
        return self._root() / _PID_NAME

    def _video_path(self) -> Path | None:
        candidate = app_data_dir() / "wallpapers" / "live-matrix.mp4"
        return candidate if candidate.is_file() else None

    def _feature_enabled(self) -> bool:
        if not self._settings_get:
            return True
        settings = self._settings_get() or {}
        features = settings.get("features") or {}
        if "live_wallpaper" not in features:
            return True
        return bool(features.get("live_wallpaper"))

    def _intensity(self) -> int:
        if not self._settings_get:
            return 55
        settings = self._settings_get() or {}
        appearance = settings.get("appearance") or {}
        parsed = parse_int(appearance.get("rain_intensity", 55))
        return 55 if parsed is None else clamp_int(parsed, 0, 100)

    def _running_pid(self) -> int | None:
        # @use: medium use — purpose: alive-check pidfile without raising into poll
        path = self._pid_path()
        if not path.is_file():
            return None
        try:
            text = path.read_text(encoding="utf-8").strip()
        except OSError:
            return None
        pid = parse_int(text)
        if pid is None or pid <= 0:
            return None
        try:
            os.kill(pid, 0)
        except OSError:
            return None
        return pid

    def available(self) -> bool:
        return True

    def snapshot(self) -> dict[str, Any]:
        # @use: medium use — purpose: Appearance live wallpaper panel
        video = self._video_path()
        backends = ["html"]
        if self.mpvpaper and video is not None:
            backends.insert(0, "mpvpaper")
        pid = self._running_pid()
        return {
            "available": True,
            "backend": backends[0],
            "backends": backends,
            "enabled": self._feature_enabled(),
            "running": pid is not None,
            "pid": pid,
            "intensity": self._intensity(),
            "mpvpaper_available": bool(self.mpvpaper),
            "video_present": video is not None,
            "wm_class": _WM_CLASS,
            "hyprland_active": bool(os.environ.get("HYPRLAND_INSTANCE_SIGNATURE")),
        }

    def command(self, name: str, payload: dict[str, Any]) -> dict[str, Any]:
        return dispatch_command(self._commands(), name, payload, adapter_id=self.id)

    def _commands(self) -> dict[str, Any]:
        return {
            "status": lambda _payload: {"ok": True, **self.snapshot()},
            "start": lambda payload: self._start(payload),
            "stop": lambda _payload: self._stop(),
            "pulse_on": lambda payload: self._start(payload),
            "pulse_off": lambda _payload: self._stop(),
        }

    def _start(self, payload: dict[str, Any]) -> dict[str, Any]:
        # @use: low use — purpose: enable flag, etch rules/script, spawn wallpaper
        if self._settings_update:
            self._settings_update({"features": {"live_wallpaper": True}})
        intensity = self._intensity()
        if "intensity" in payload:
            parsed = parse_int(payload["intensity"])
            intensity = intensity if parsed is None else clamp_int(parsed, 0, 100)
        root = self._root()
        root.mkdir(parents=True, exist_ok=True)
        rules_path = root / "hypr-live-wallpaper.conf"
        script_path = root / "live-wallpaper-generated.sh"
        rules_path.write_text(etch_hypr_rules(), encoding="utf-8")
        source_line = f"source = {rules_path}"
        appended = ensure_hypr_live_source(self._hypr_path(), source_line)
        video = self._video_path()
        script_path.write_text(
            etch_launcher_script(
                python=self.python,
                intensity=intensity,
                mpvpaper=self.mpvpaper,
                video=video,
            ),
            encoding="utf-8",
        )
        try:
            script_path.chmod(script_path.stat().st_mode | stat.S_IXUSR)
        except OSError:
            pass
        # Stop any previous instance first.
        self._stop(clear_flag=False)
        # Prefer mpvpaper when video exists; else HTML/DV.rain python module.
        argv = (
            [self.mpvpaper, "-o", "no-audio --loop", "*", str(video)]
            if self.mpvpaper and video is not None
            else [
                self.python,
                "-m",
                "lmdesktopplus",
                "--live-wallpaper",
                "--rain-intensity",
                str(intensity),
            ]
        )
        try:
            pid = spawn(argv)
            self._pid_path().write_text(f"{pid}\n", encoding="utf-8")
        except OSError as exc:
            return command_error("internal_error", str(exc))
        # Brief settle so running probe is reliable.
        time.sleep(0.05)
        snap = self.snapshot()
        return {"ok": True, **snap, "rules_appended": appended, "script": str(script_path)}

    def _stop(self, *, clear_flag: bool = True) -> dict[str, Any]:
        # @use: low use — purpose: kill live wallpaper pid and optional feature clear
        pid = self._running_pid()
        if pid is not None:
            try:
                os.kill(pid, signal.SIGTERM)
            except OSError:
                pass
        try:
            self._pid_path().unlink(missing_ok=True)
        except OSError:
            pass
        if clear_flag and self._settings_update:
            self._settings_update({"features": {"live_wallpaper": False}})
        snap = self.snapshot()
        return {"ok": True, **snap}
